### PR TITLE
add fun liquid fill gauge visualization

### PR DESCRIPTION
**Pull request by RichardCzechowski**
Fun drop in replacement for single value

gauge

Notes:
Needs error handling. Plan to add ability to set max value based on second measure- but not tonight

based on http://bl.ocks.org/brattonc/5e5ce9beee483220e2f6

### CODE REVIEW

**Comment by joshmoskovitz** [comment]
Ha this is fun! 🎆

**Comment by githoov** [comment]
👍

**Comment by ericfeinstein** [comment]
This is cool -- 1 or 2 measures accepted?

**Comment by RichardCzechowski** [comment]
Currently one measure. I plan to allow the Max fill value to be based on a second measure.

**Comment by RichardCzechowski** [comment]
It could probably use better error handling. But I think I'm done with this guy for now.

**Pull request merged**
